import { evalSummary } from "../data/evalSummary";

function pct(x) {
  return `${Math.round(x * 100)}%`;
}

export default function Methodology() {
  return (
    <main className="methodology">
      <section>
        <h2>What this is</h2>
        <p>
          RAG over a synthetic patient population, built to demonstrate real
          retrieval-augmented generation engineering: retrieval that's visibly
          correct, a documented eval against ground truth, and an honest accounting
          of where vector search alone isn't the right tool.
        </p>
      </section>

      <section>
        <h2>Data</h2>
        <p>
          ~1000 synthetic patients generated by{" "}
          <a href="https://github.com/synthetichealth/synthea" target="_blank" rel="noreferrer">
            Synthea
          </a>
          , an open-source synthetic EHR generator. No real patient data anywhere in
          this project. Each patient's most recent 5 years of history is indexed:
          conditions, medications, encounters, lab observations, and SOAP-style
          clinical notes &mdash; about 93,000 retrievable chunks in total.
        </p>
      </section>

      <section>
        <h2>Retrieval architecture</h2>
        <p>
          Two modes, both backed by the same indexed data:
        </p>
        <ul>
          <li>
            <strong>Patient-scoped chat</strong> &mdash; vector retrieval filtered to
            one patient's records by metadata (patient ID).
          </li>
          <li>
            <strong>Population chat</strong> &mdash; a deterministic, rule-based
            router decides per question whether it's a counting/aggregate question
            ("how many patients have X") or a descriptive one. Counting questions are
            answered by a real SQL query against the structured Synthea tables, not
            vector search &mdash; similarity search retrieves <em>relevant</em>{" "}
            records, not <em>all</em> matching records, so it systematically
            undercounts. Descriptive questions ("what's commonly seen alongside X")
            use vector RAG.
          </li>
        </ul>
        <p>
          Embeddings are <code>all-MiniLM-L6-v2</code> (local, no per-call cost), the
          index is a plain in-memory vector matrix built offline (no ANN index needed
          at ~93k chunks &mdash; brute-force cosine similarity is a few milliseconds),
          and the LLM is Groq's free API tier.
        </p>
      </section>

      <section>
        <h2>Eval results</h2>
        <p>
          40 hand-crafted questions (20 patient-scoped, 20 population-scoped), each
          with an answer mechanically derivable from the underlying structured data
          &mdash; not guessed. Retrieval/router routing is scored automatically
          against known-correct behavior; answer correctness is graded manually
          against the ground truth (not LLM-as-judge).
        </p>
        <div className="eval-grid">
          <div className="eval-stat">
            <div className="eval-stat-value">{pct(evalSummary.answer_accuracy)}</div>
            <div className="eval-stat-label">Overall answer accuracy</div>
          </div>
          <div className="eval-stat">
            <div className="eval-stat-value">{pct(evalSummary.router_accuracy)}</div>
            <div className="eval-stat-label">Router routing accuracy</div>
          </div>
          <div className="eval-stat">
            <div className="eval-stat-value">
              {pct(evalSummary.by_mode.population.answer_accuracy)}
            </div>
            <div className="eval-stat-label">
              Population mode accuracy ({evalSummary.by_mode.population.n} questions)
            </div>
          </div>
          <div className="eval-stat">
            <div className="eval-stat-value">
              {pct(evalSummary.by_mode.patient.answer_accuracy)}
            </div>
            <div className="eval-stat-label">
              Patient mode accuracy ({evalSummary.by_mode.patient.n} questions)
            </div>
          </div>
        </div>
      </section>

      <section>
        <h2>Known limitation: patient-mode list completeness</h2>
        <p>
          Population-mode counting questions are 100% accurate &mdash; the
          structured-query router path is deterministic and exact. Patient-mode
          "list all X" questions score lower (35% under strict all-or-nothing
          grading: any missing or extra item counts as wrong) for a specific,
          understood reason: retrieval returns a fixed number of chunks per query,
          and a patient with more diagnosed conditions or medications than that
          limit will get an incomplete list back, no matter how good the prompt is.
        </p>
        <p>
          Two prompt-level fixes were tried and measured during development: telling
          the model to trust structured <code>[medication]</code>/<code>[condition]</code>{" "}
          records over clinical-note narrative text (this eliminated most
          hallucinated-medication errors), and increasing retrieval depth for
          patient-mode queries (this improved recall but didn't fully solve
          completeness for patients with unusually long histories). Both are
          reflected in the current numbers above &mdash; they were not reverted
          after measuring a low first-pass score.
        </p>
        <p>
          <strong>Planned next step (not yet built):</strong> re-run the eval after
          expanding the question set and tuning retrieval further, to see whether
          list-completeness improves with a more targeted retrieval strategy per
          record type rather than one flat top-k call.
        </p>
      </section>
    </main>
  );
}
